CREATE TABLE IF NOT EXISTS theaters (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(36) NOT NULL,
    city VARCHAR(45) NOT NULL,
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);